/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppColdproProjetosRouteImport } from './routes/_app/coldpro/projetos'
import { Route as AppColdproDesenvolvimentoRouteImport } from './routes/_app/coldpro/desenvolvimento'
import { Route as AppColdproDashboardRouteImport } from './routes/_app/coldpro/dashboard'
import { Route as AppColdproCatalogo480RouteImport } from './routes/_app/coldpro/catalogo-480'
import { Route as AppColdproCatalogoRouteImport } from './routes/_app/coldpro/catalogo'
import { Route as AppAdminUnilabImportRouteImport } from './routes/_app/admin_.unilab-import'
import { Route as AppAdminColdproImportRouteImport } from './routes/_app/admin_.coldpro-import'
import { Route as AppColdproEquipamentosIndexRouteImport } from './routes/_app/coldpro/equipamentos/index'
import { Route as AppAdminDatabaseIndexRouteImport } from './routes/_app/admin_.database.index'
import { Route as AppColdproEquipamentosIdRouteImport } from './routes/_app/coldpro/equipamentos/$id'
import { Route as AppColdproAdminRevisaoTecnicaRouteImport } from './routes/_app/coldpro/admin.revisao-tecnica'
import { Route as AppColdproAdminBancoTecnicoRouteImport } from './routes/_app/coldpro/admin.banco-tecnico'
import { Route as AppAdminDatabaseModeRouteImport } from './routes/_app/admin_.database.$mode'
import { Route as AppColdproEquipamentosIdCoilSimulatorRouteImport } from './routes/_app/coldpro/equipamentos/$id/coil-simulator'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproProjetosRoute = AppColdproProjetosRouteImport.update({
  id: '/coldpro/projetos',
  path: '/coldpro/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproDesenvolvimentoRoute =
  AppColdproDesenvolvimentoRouteImport.update({
    id: '/coldpro/desenvolvimento',
    path: '/coldpro/desenvolvimento',
    getParentRoute: () => AppRoute,
  } as any)
const AppColdproDashboardRoute = AppColdproDashboardRouteImport.update({
  id: '/coldpro/dashboard',
  path: '/coldpro/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproCatalogo480Route = AppColdproCatalogo480RouteImport.update({
  id: '/coldpro/catalogo-480',
  path: '/coldpro/catalogo-480',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproCatalogoRoute = AppColdproCatalogoRouteImport.update({
  id: '/coldpro/catalogo',
  path: '/coldpro/catalogo',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUnilabImportRoute = AppAdminUnilabImportRouteImport.update({
  id: '/admin_/unilab-import',
  path: '/admin/unilab-import',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminColdproImportRoute = AppAdminColdproImportRouteImport.update({
  id: '/admin_/coldpro-import',
  path: '/admin/coldpro-import',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproEquipamentosIndexRoute =
  AppColdproEquipamentosIndexRouteImport.update({
    id: '/coldpro/equipamentos/',
    path: '/coldpro/equipamentos/',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminDatabaseIndexRoute = AppAdminDatabaseIndexRouteImport.update({
  id: '/admin_/database/',
  path: '/admin/database/',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproEquipamentosIdRoute =
  AppColdproEquipamentosIdRouteImport.update({
    id: '/coldpro/equipamentos/$id',
    path: '/coldpro/equipamentos/$id',
    getParentRoute: () => AppRoute,
  } as any)
const AppColdproAdminRevisaoTecnicaRoute =
  AppColdproAdminRevisaoTecnicaRouteImport.update({
    id: '/coldpro/admin/revisao-tecnica',
    path: '/coldpro/admin/revisao-tecnica',
    getParentRoute: () => AppRoute,
  } as any)
const AppColdproAdminBancoTecnicoRoute =
  AppColdproAdminBancoTecnicoRouteImport.update({
    id: '/coldpro/admin/banco-tecnico',
    path: '/coldpro/admin/banco-tecnico',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminDatabaseModeRoute = AppAdminDatabaseModeRouteImport.update({
  id: '/admin_/database/$mode',
  path: '/admin/database/$mode',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproEquipamentosIdCoilSimulatorRoute =
  AppColdproEquipamentosIdCoilSimulatorRouteImport.update({
    id: '/coil-simulator',
    path: '/coil-simulator',
    getParentRoute: () => AppColdproEquipamentosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/admin/coldpro-import': typeof AppAdminColdproImportRoute
  '/admin/unilab-import': typeof AppAdminUnilabImportRoute
  '/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/coldpro/catalogo-480': typeof AppColdproCatalogo480Route
  '/coldpro/dashboard': typeof AppColdproDashboardRoute
  '/coldpro/desenvolvimento': typeof AppColdproDesenvolvimentoRoute
  '/coldpro/projetos': typeof AppColdproProjetosRoute
  '/admin/database/$mode': typeof AppAdminDatabaseModeRoute
  '/coldpro/admin/banco-tecnico': typeof AppColdproAdminBancoTecnicoRoute
  '/coldpro/admin/revisao-tecnica': typeof AppColdproAdminRevisaoTecnicaRoute
  '/coldpro/equipamentos/$id': typeof AppColdproEquipamentosIdRouteWithChildren
  '/admin/database/': typeof AppAdminDatabaseIndexRoute
  '/coldpro/equipamentos/': typeof AppColdproEquipamentosIndexRoute
  '/coldpro/equipamentos/$id/coil-simulator': typeof AppColdproEquipamentosIdCoilSimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/admin/coldpro-import': typeof AppAdminColdproImportRoute
  '/admin/unilab-import': typeof AppAdminUnilabImportRoute
  '/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/coldpro/catalogo-480': typeof AppColdproCatalogo480Route
  '/coldpro/dashboard': typeof AppColdproDashboardRoute
  '/coldpro/desenvolvimento': typeof AppColdproDesenvolvimentoRoute
  '/coldpro/projetos': typeof AppColdproProjetosRoute
  '/admin/database/$mode': typeof AppAdminDatabaseModeRoute
  '/coldpro/admin/banco-tecnico': typeof AppColdproAdminBancoTecnicoRoute
  '/coldpro/admin/revisao-tecnica': typeof AppColdproAdminRevisaoTecnicaRoute
  '/coldpro/equipamentos/$id': typeof AppColdproEquipamentosIdRouteWithChildren
  '/admin/database': typeof AppAdminDatabaseIndexRoute
  '/coldpro/equipamentos': typeof AppColdproEquipamentosIndexRoute
  '/coldpro/equipamentos/$id/coil-simulator': typeof AppColdproEquipamentosIdCoilSimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/admin_/coldpro-import': typeof AppAdminColdproImportRoute
  '/_app/admin_/unilab-import': typeof AppAdminUnilabImportRoute
  '/_app/coldpro/catalogo': typeof AppColdproCatalogoRoute
  '/_app/coldpro/catalogo-480': typeof AppColdproCatalogo480Route
  '/_app/coldpro/dashboard': typeof AppColdproDashboardRoute
  '/_app/coldpro/desenvolvimento': typeof AppColdproDesenvolvimentoRoute
  '/_app/coldpro/projetos': typeof AppColdproProjetosRoute
  '/_app/admin_/database/$mode': typeof AppAdminDatabaseModeRoute
  '/_app/coldpro/admin/banco-tecnico': typeof AppColdproAdminBancoTecnicoRoute
  '/_app/coldpro/admin/revisao-tecnica': typeof AppColdproAdminRevisaoTecnicaRoute
  '/_app/coldpro/equipamentos/$id': typeof AppColdproEquipamentosIdRouteWithChildren
  '/_app/admin_/database/': typeof AppAdminDatabaseIndexRoute
  '/_app/coldpro/equipamentos/': typeof AppColdproEquipamentosIndexRoute
  '/_app/coldpro/equipamentos/$id/coil-simulator': typeof AppColdproEquipamentosIdCoilSimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/coldpro-import'
    | '/admin/unilab-import'
    | '/coldpro/catalogo'
    | '/coldpro/catalogo-480'
    | '/coldpro/dashboard'
    | '/coldpro/desenvolvimento'
    | '/coldpro/projetos'
    | '/admin/database/$mode'
    | '/coldpro/admin/banco-tecnico'
    | '/coldpro/admin/revisao-tecnica'
    | '/coldpro/equipamentos/$id'
    | '/admin/database/'
    | '/coldpro/equipamentos/'
    | '/coldpro/equipamentos/$id/coil-simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/admin/coldpro-import'
    | '/admin/unilab-import'
    | '/coldpro/catalogo'
    | '/coldpro/catalogo-480'
    | '/coldpro/dashboard'
    | '/coldpro/desenvolvimento'
    | '/coldpro/projetos'
    | '/admin/database/$mode'
    | '/coldpro/admin/banco-tecnico'
    | '/coldpro/admin/revisao-tecnica'
    | '/coldpro/equipamentos/$id'
    | '/admin/database'
    | '/coldpro/equipamentos'
    | '/coldpro/equipamentos/$id/coil-simulator'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/admin_/coldpro-import'
    | '/_app/admin_/unilab-import'
    | '/_app/coldpro/catalogo'
    | '/_app/coldpro/catalogo-480'
    | '/_app/coldpro/dashboard'
    | '/_app/coldpro/desenvolvimento'
    | '/_app/coldpro/projetos'
    | '/_app/admin_/database/$mode'
    | '/_app/coldpro/admin/banco-tecnico'
    | '/_app/coldpro/admin/revisao-tecnica'
    | '/_app/coldpro/equipamentos/$id'
    | '/_app/admin_/database/'
    | '/_app/coldpro/equipamentos/'
    | '/_app/coldpro/equipamentos/$id/coil-simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/projetos': {
      id: '/_app/coldpro/projetos'
      path: '/coldpro/projetos'
      fullPath: '/coldpro/projetos'
      preLoaderRoute: typeof AppColdproProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/desenvolvimento': {
      id: '/_app/coldpro/desenvolvimento'
      path: '/coldpro/desenvolvimento'
      fullPath: '/coldpro/desenvolvimento'
      preLoaderRoute: typeof AppColdproDesenvolvimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/dashboard': {
      id: '/_app/coldpro/dashboard'
      path: '/coldpro/dashboard'
      fullPath: '/coldpro/dashboard'
      preLoaderRoute: typeof AppColdproDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/catalogo-480': {
      id: '/_app/coldpro/catalogo-480'
      path: '/coldpro/catalogo-480'
      fullPath: '/coldpro/catalogo-480'
      preLoaderRoute: typeof AppColdproCatalogo480RouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/catalogo': {
      id: '/_app/coldpro/catalogo'
      path: '/coldpro/catalogo'
      fullPath: '/coldpro/catalogo'
      preLoaderRoute: typeof AppColdproCatalogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin_/unilab-import': {
      id: '/_app/admin_/unilab-import'
      path: '/admin/unilab-import'
      fullPath: '/admin/unilab-import'
      preLoaderRoute: typeof AppAdminUnilabImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin_/coldpro-import': {
      id: '/_app/admin_/coldpro-import'
      path: '/admin/coldpro-import'
      fullPath: '/admin/coldpro-import'
      preLoaderRoute: typeof AppAdminColdproImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/equipamentos/': {
      id: '/_app/coldpro/equipamentos/'
      path: '/coldpro/equipamentos'
      fullPath: '/coldpro/equipamentos/'
      preLoaderRoute: typeof AppColdproEquipamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin_/database/': {
      id: '/_app/admin_/database/'
      path: '/admin/database'
      fullPath: '/admin/database/'
      preLoaderRoute: typeof AppAdminDatabaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/equipamentos/$id': {
      id: '/_app/coldpro/equipamentos/$id'
      path: '/coldpro/equipamentos/$id'
      fullPath: '/coldpro/equipamentos/$id'
      preLoaderRoute: typeof AppColdproEquipamentosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/admin/revisao-tecnica': {
      id: '/_app/coldpro/admin/revisao-tecnica'
      path: '/coldpro/admin/revisao-tecnica'
      fullPath: '/coldpro/admin/revisao-tecnica'
      preLoaderRoute: typeof AppColdproAdminRevisaoTecnicaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/admin/banco-tecnico': {
      id: '/_app/coldpro/admin/banco-tecnico'
      path: '/coldpro/admin/banco-tecnico'
      fullPath: '/coldpro/admin/banco-tecnico'
      preLoaderRoute: typeof AppColdproAdminBancoTecnicoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin_/database/$mode': {
      id: '/_app/admin_/database/$mode'
      path: '/admin/database/$mode'
      fullPath: '/admin/database/$mode'
      preLoaderRoute: typeof AppAdminDatabaseModeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/equipamentos/$id/coil-simulator': {
      id: '/_app/coldpro/equipamentos/$id/coil-simulator'
      path: '/coil-simulator'
      fullPath: '/coldpro/equipamentos/$id/coil-simulator'
      preLoaderRoute: typeof AppColdproEquipamentosIdCoilSimulatorRouteImport
      parentRoute: typeof AppColdproEquipamentosIdRoute
    }
  }
}

interface AppColdproEquipamentosIdRouteChildren {
  AppColdproEquipamentosIdCoilSimulatorRoute: typeof AppColdproEquipamentosIdCoilSimulatorRoute
}

const AppColdproEquipamentosIdRouteChildren: AppColdproEquipamentosIdRouteChildren =
  {
    AppColdproEquipamentosIdCoilSimulatorRoute:
      AppColdproEquipamentosIdCoilSimulatorRoute,
  }

const AppColdproEquipamentosIdRouteWithChildren =
  AppColdproEquipamentosIdRoute._addFileChildren(
    AppColdproEquipamentosIdRouteChildren,
  )

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppAdminColdproImportRoute: typeof AppAdminColdproImportRoute
  AppAdminUnilabImportRoute: typeof AppAdminUnilabImportRoute
  AppColdproCatalogoRoute: typeof AppColdproCatalogoRoute
  AppColdproCatalogo480Route: typeof AppColdproCatalogo480Route
  AppColdproDashboardRoute: typeof AppColdproDashboardRoute
  AppColdproDesenvolvimentoRoute: typeof AppColdproDesenvolvimentoRoute
  AppColdproProjetosRoute: typeof AppColdproProjetosRoute
  AppAdminDatabaseModeRoute: typeof AppAdminDatabaseModeRoute
  AppColdproAdminBancoTecnicoRoute: typeof AppColdproAdminBancoTecnicoRoute
  AppColdproAdminRevisaoTecnicaRoute: typeof AppColdproAdminRevisaoTecnicaRoute
  AppColdproEquipamentosIdRoute: typeof AppColdproEquipamentosIdRouteWithChildren
  AppAdminDatabaseIndexRoute: typeof AppAdminDatabaseIndexRoute
  AppColdproEquipamentosIndexRoute: typeof AppColdproEquipamentosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppAdminColdproImportRoute: AppAdminColdproImportRoute,
  AppAdminUnilabImportRoute: AppAdminUnilabImportRoute,
  AppColdproCatalogoRoute: AppColdproCatalogoRoute,
  AppColdproCatalogo480Route: AppColdproCatalogo480Route,
  AppColdproDashboardRoute: AppColdproDashboardRoute,
  AppColdproDesenvolvimentoRoute: AppColdproDesenvolvimentoRoute,
  AppColdproProjetosRoute: AppColdproProjetosRoute,
  AppAdminDatabaseModeRoute: AppAdminDatabaseModeRoute,
  AppColdproAdminBancoTecnicoRoute: AppColdproAdminBancoTecnicoRoute,
  AppColdproAdminRevisaoTecnicaRoute: AppColdproAdminRevisaoTecnicaRoute,
  AppColdproEquipamentosIdRoute: AppColdproEquipamentosIdRouteWithChildren,
  AppAdminDatabaseIndexRoute: AppAdminDatabaseIndexRoute,
  AppColdproEquipamentosIndexRoute: AppColdproEquipamentosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
