/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppColdproRouteImport } from './routes/_app/coldpro'
import { Route as AppColdproIndexRouteImport } from './routes/_app/coldpro.index'
import { Route as AppColdproUnilabRouteImport } from './routes/_app/coldpro.unilab'
import { Route as AppColdproSimulationRouteImport } from './routes/_app/coldpro.simulation'
import { Route as AppColdproRegistryRouteImport } from './routes/_app/coldpro.registry'
import { Route as AppColdproRecordRouteImport } from './routes/_app/coldpro.record'
import { Route as AppColdproMontagemRouteImport } from './routes/_app/coldpro.montagem'
import { Route as AppColdproMapRouteImport } from './routes/_app/coldpro.map'
import { Route as AppColdproFichaTecnicaRouteImport } from './routes/_app/coldpro.ficha-tecnica'
import { Route as AppColdproExportRouteImport } from './routes/_app/coldpro.export'
import { Route as AppColdproCurveRouteImport } from './routes/_app/coldpro.curve'
import { Route as AppColdproComponentsRouteImport } from './routes/_app/coldpro.components'
import { Route as AppColdproCatalogRouteImport } from './routes/_app/coldpro.catalog'
import { Route as AppColdproAuditRouteImport } from './routes/_app/coldpro.audit'
import { Route as AppColdproAssemblyRouteImport } from './routes/_app/coldpro.assembly'
import { Route as AppColdproUnilabWorkspaceRouteImport } from './routes/_app/coldpro.unilab.workspace'
import { Route as AppColdproUnilabSystemsHeatPumpRouteImport } from './routes/_app/coldpro.unilab.systems.heat-pump'
import { Route as AppColdproUnilabSystemsDxCompleteRouteImport } from './routes/_app/coldpro.unilab.systems.dx-complete'
import { Route as AppColdproUnilabSystemsDehumidificationRouteImport } from './routes/_app/coldpro.unilab.systems.dehumidification'
import { Route as AppColdproUnilabSystemsColdRoomRouteImport } from './routes/_app/coldpro.unilab.systems.cold-room'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproRoute = AppColdproRouteImport.update({
  id: '/coldpro',
  path: '/coldpro',
  getParentRoute: () => AppRoute,
} as any)
const AppColdproIndexRoute = AppColdproIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproUnilabRoute = AppColdproUnilabRouteImport.update({
  id: '/unilab',
  path: '/unilab',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproSimulationRoute = AppColdproSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproRegistryRoute = AppColdproRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproRecordRoute = AppColdproRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproMontagemRoute = AppColdproMontagemRouteImport.update({
  id: '/montagem',
  path: '/montagem',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproMapRoute = AppColdproMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproFichaTecnicaRoute = AppColdproFichaTecnicaRouteImport.update({
  id: '/ficha-tecnica',
  path: '/ficha-tecnica',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproExportRoute = AppColdproExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproCurveRoute = AppColdproCurveRouteImport.update({
  id: '/curve',
  path: '/curve',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproComponentsRoute = AppColdproComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproCatalogRoute = AppColdproCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproAuditRoute = AppColdproAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproAssemblyRoute = AppColdproAssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => AppColdproRoute,
} as any)
const AppColdproUnilabWorkspaceRoute =
  AppColdproUnilabWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AppColdproUnilabRoute,
  } as any)
const AppColdproUnilabSystemsHeatPumpRoute =
  AppColdproUnilabSystemsHeatPumpRouteImport.update({
    id: '/systems/heat-pump',
    path: '/systems/heat-pump',
    getParentRoute: () => AppColdproUnilabRoute,
  } as any)
const AppColdproUnilabSystemsDxCompleteRoute =
  AppColdproUnilabSystemsDxCompleteRouteImport.update({
    id: '/systems/dx-complete',
    path: '/systems/dx-complete',
    getParentRoute: () => AppColdproUnilabRoute,
  } as any)
const AppColdproUnilabSystemsDehumidificationRoute =
  AppColdproUnilabSystemsDehumidificationRouteImport.update({
    id: '/systems/dehumidification',
    path: '/systems/dehumidification',
    getParentRoute: () => AppColdproUnilabRoute,
  } as any)
const AppColdproUnilabSystemsColdRoomRoute =
  AppColdproUnilabSystemsColdRoomRouteImport.update({
    id: '/systems/cold-room',
    path: '/systems/cold-room',
    getParentRoute: () => AppColdproUnilabRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coldpro': typeof AppColdproRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/coldpro/assembly': typeof AppColdproAssemblyRoute
  '/coldpro/audit': typeof AppColdproAuditRoute
  '/coldpro/catalog': typeof AppColdproCatalogRoute
  '/coldpro/components': typeof AppColdproComponentsRoute
  '/coldpro/curve': typeof AppColdproCurveRoute
  '/coldpro/export': typeof AppColdproExportRoute
  '/coldpro/ficha-tecnica': typeof AppColdproFichaTecnicaRoute
  '/coldpro/map': typeof AppColdproMapRoute
  '/coldpro/montagem': typeof AppColdproMontagemRoute
  '/coldpro/record': typeof AppColdproRecordRoute
  '/coldpro/registry': typeof AppColdproRegistryRoute
  '/coldpro/simulation': typeof AppColdproSimulationRoute
  '/coldpro/unilab': typeof AppColdproUnilabRouteWithChildren
  '/coldpro/': typeof AppColdproIndexRoute
  '/coldpro/unilab/workspace': typeof AppColdproUnilabWorkspaceRoute
  '/coldpro/unilab/systems/cold-room': typeof AppColdproUnilabSystemsColdRoomRoute
  '/coldpro/unilab/systems/dehumidification': typeof AppColdproUnilabSystemsDehumidificationRoute
  '/coldpro/unilab/systems/dx-complete': typeof AppColdproUnilabSystemsDxCompleteRoute
  '/coldpro/unilab/systems/heat-pump': typeof AppColdproUnilabSystemsHeatPumpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AppDashboardRoute
  '/coldpro/assembly': typeof AppColdproAssemblyRoute
  '/coldpro/audit': typeof AppColdproAuditRoute
  '/coldpro/catalog': typeof AppColdproCatalogRoute
  '/coldpro/components': typeof AppColdproComponentsRoute
  '/coldpro/curve': typeof AppColdproCurveRoute
  '/coldpro/export': typeof AppColdproExportRoute
  '/coldpro/ficha-tecnica': typeof AppColdproFichaTecnicaRoute
  '/coldpro/map': typeof AppColdproMapRoute
  '/coldpro/montagem': typeof AppColdproMontagemRoute
  '/coldpro/record': typeof AppColdproRecordRoute
  '/coldpro/registry': typeof AppColdproRegistryRoute
  '/coldpro/simulation': typeof AppColdproSimulationRoute
  '/coldpro/unilab': typeof AppColdproUnilabRouteWithChildren
  '/coldpro': typeof AppColdproIndexRoute
  '/coldpro/unilab/workspace': typeof AppColdproUnilabWorkspaceRoute
  '/coldpro/unilab/systems/cold-room': typeof AppColdproUnilabSystemsColdRoomRoute
  '/coldpro/unilab/systems/dehumidification': typeof AppColdproUnilabSystemsDehumidificationRoute
  '/coldpro/unilab/systems/dx-complete': typeof AppColdproUnilabSystemsDxCompleteRoute
  '/coldpro/unilab/systems/heat-pump': typeof AppColdproUnilabSystemsHeatPumpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/coldpro': typeof AppColdproRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/coldpro/assembly': typeof AppColdproAssemblyRoute
  '/_app/coldpro/audit': typeof AppColdproAuditRoute
  '/_app/coldpro/catalog': typeof AppColdproCatalogRoute
  '/_app/coldpro/components': typeof AppColdproComponentsRoute
  '/_app/coldpro/curve': typeof AppColdproCurveRoute
  '/_app/coldpro/export': typeof AppColdproExportRoute
  '/_app/coldpro/ficha-tecnica': typeof AppColdproFichaTecnicaRoute
  '/_app/coldpro/map': typeof AppColdproMapRoute
  '/_app/coldpro/montagem': typeof AppColdproMontagemRoute
  '/_app/coldpro/record': typeof AppColdproRecordRoute
  '/_app/coldpro/registry': typeof AppColdproRegistryRoute
  '/_app/coldpro/simulation': typeof AppColdproSimulationRoute
  '/_app/coldpro/unilab': typeof AppColdproUnilabRouteWithChildren
  '/_app/coldpro/': typeof AppColdproIndexRoute
  '/_app/coldpro/unilab/workspace': typeof AppColdproUnilabWorkspaceRoute
  '/_app/coldpro/unilab/systems/cold-room': typeof AppColdproUnilabSystemsColdRoomRoute
  '/_app/coldpro/unilab/systems/dehumidification': typeof AppColdproUnilabSystemsDehumidificationRoute
  '/_app/coldpro/unilab/systems/dx-complete': typeof AppColdproUnilabSystemsDxCompleteRoute
  '/_app/coldpro/unilab/systems/heat-pump': typeof AppColdproUnilabSystemsHeatPumpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coldpro'
    | '/dashboard'
    | '/coldpro/assembly'
    | '/coldpro/audit'
    | '/coldpro/catalog'
    | '/coldpro/components'
    | '/coldpro/curve'
    | '/coldpro/export'
    | '/coldpro/ficha-tecnica'
    | '/coldpro/map'
    | '/coldpro/montagem'
    | '/coldpro/record'
    | '/coldpro/registry'
    | '/coldpro/simulation'
    | '/coldpro/unilab'
    | '/coldpro/'
    | '/coldpro/unilab/workspace'
    | '/coldpro/unilab/systems/cold-room'
    | '/coldpro/unilab/systems/dehumidification'
    | '/coldpro/unilab/systems/dx-complete'
    | '/coldpro/unilab/systems/heat-pump'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/coldpro/assembly'
    | '/coldpro/audit'
    | '/coldpro/catalog'
    | '/coldpro/components'
    | '/coldpro/curve'
    | '/coldpro/export'
    | '/coldpro/ficha-tecnica'
    | '/coldpro/map'
    | '/coldpro/montagem'
    | '/coldpro/record'
    | '/coldpro/registry'
    | '/coldpro/simulation'
    | '/coldpro/unilab'
    | '/coldpro'
    | '/coldpro/unilab/workspace'
    | '/coldpro/unilab/systems/cold-room'
    | '/coldpro/unilab/systems/dehumidification'
    | '/coldpro/unilab/systems/dx-complete'
    | '/coldpro/unilab/systems/heat-pump'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/coldpro'
    | '/_app/dashboard'
    | '/_app/coldpro/assembly'
    | '/_app/coldpro/audit'
    | '/_app/coldpro/catalog'
    | '/_app/coldpro/components'
    | '/_app/coldpro/curve'
    | '/_app/coldpro/export'
    | '/_app/coldpro/ficha-tecnica'
    | '/_app/coldpro/map'
    | '/_app/coldpro/montagem'
    | '/_app/coldpro/record'
    | '/_app/coldpro/registry'
    | '/_app/coldpro/simulation'
    | '/_app/coldpro/unilab'
    | '/_app/coldpro/'
    | '/_app/coldpro/unilab/workspace'
    | '/_app/coldpro/unilab/systems/cold-room'
    | '/_app/coldpro/unilab/systems/dehumidification'
    | '/_app/coldpro/unilab/systems/dx-complete'
    | '/_app/coldpro/unilab/systems/heat-pump'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro': {
      id: '/_app/coldpro'
      path: '/coldpro'
      fullPath: '/coldpro'
      preLoaderRoute: typeof AppColdproRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coldpro/': {
      id: '/_app/coldpro/'
      path: '/'
      fullPath: '/coldpro/'
      preLoaderRoute: typeof AppColdproIndexRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/unilab': {
      id: '/_app/coldpro/unilab'
      path: '/unilab'
      fullPath: '/coldpro/unilab'
      preLoaderRoute: typeof AppColdproUnilabRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/simulation': {
      id: '/_app/coldpro/simulation'
      path: '/simulation'
      fullPath: '/coldpro/simulation'
      preLoaderRoute: typeof AppColdproSimulationRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/registry': {
      id: '/_app/coldpro/registry'
      path: '/registry'
      fullPath: '/coldpro/registry'
      preLoaderRoute: typeof AppColdproRegistryRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/record': {
      id: '/_app/coldpro/record'
      path: '/record'
      fullPath: '/coldpro/record'
      preLoaderRoute: typeof AppColdproRecordRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/montagem': {
      id: '/_app/coldpro/montagem'
      path: '/montagem'
      fullPath: '/coldpro/montagem'
      preLoaderRoute: typeof AppColdproMontagemRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/map': {
      id: '/_app/coldpro/map'
      path: '/map'
      fullPath: '/coldpro/map'
      preLoaderRoute: typeof AppColdproMapRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/ficha-tecnica': {
      id: '/_app/coldpro/ficha-tecnica'
      path: '/ficha-tecnica'
      fullPath: '/coldpro/ficha-tecnica'
      preLoaderRoute: typeof AppColdproFichaTecnicaRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/export': {
      id: '/_app/coldpro/export'
      path: '/export'
      fullPath: '/coldpro/export'
      preLoaderRoute: typeof AppColdproExportRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/curve': {
      id: '/_app/coldpro/curve'
      path: '/curve'
      fullPath: '/coldpro/curve'
      preLoaderRoute: typeof AppColdproCurveRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/components': {
      id: '/_app/coldpro/components'
      path: '/components'
      fullPath: '/coldpro/components'
      preLoaderRoute: typeof AppColdproComponentsRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/catalog': {
      id: '/_app/coldpro/catalog'
      path: '/catalog'
      fullPath: '/coldpro/catalog'
      preLoaderRoute: typeof AppColdproCatalogRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/audit': {
      id: '/_app/coldpro/audit'
      path: '/audit'
      fullPath: '/coldpro/audit'
      preLoaderRoute: typeof AppColdproAuditRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/assembly': {
      id: '/_app/coldpro/assembly'
      path: '/assembly'
      fullPath: '/coldpro/assembly'
      preLoaderRoute: typeof AppColdproAssemblyRouteImport
      parentRoute: typeof AppColdproRoute
    }
    '/_app/coldpro/unilab/workspace': {
      id: '/_app/coldpro/unilab/workspace'
      path: '/workspace'
      fullPath: '/coldpro/unilab/workspace'
      preLoaderRoute: typeof AppColdproUnilabWorkspaceRouteImport
      parentRoute: typeof AppColdproUnilabRoute
    }
    '/_app/coldpro/unilab/systems/heat-pump': {
      id: '/_app/coldpro/unilab/systems/heat-pump'
      path: '/systems/heat-pump'
      fullPath: '/coldpro/unilab/systems/heat-pump'
      preLoaderRoute: typeof AppColdproUnilabSystemsHeatPumpRouteImport
      parentRoute: typeof AppColdproUnilabRoute
    }
    '/_app/coldpro/unilab/systems/dx-complete': {
      id: '/_app/coldpro/unilab/systems/dx-complete'
      path: '/systems/dx-complete'
      fullPath: '/coldpro/unilab/systems/dx-complete'
      preLoaderRoute: typeof AppColdproUnilabSystemsDxCompleteRouteImport
      parentRoute: typeof AppColdproUnilabRoute
    }
    '/_app/coldpro/unilab/systems/dehumidification': {
      id: '/_app/coldpro/unilab/systems/dehumidification'
      path: '/systems/dehumidification'
      fullPath: '/coldpro/unilab/systems/dehumidification'
      preLoaderRoute: typeof AppColdproUnilabSystemsDehumidificationRouteImport
      parentRoute: typeof AppColdproUnilabRoute
    }
    '/_app/coldpro/unilab/systems/cold-room': {
      id: '/_app/coldpro/unilab/systems/cold-room'
      path: '/systems/cold-room'
      fullPath: '/coldpro/unilab/systems/cold-room'
      preLoaderRoute: typeof AppColdproUnilabSystemsColdRoomRouteImport
      parentRoute: typeof AppColdproUnilabRoute
    }
  }
}

interface AppColdproUnilabRouteChildren {
  AppColdproUnilabWorkspaceRoute: typeof AppColdproUnilabWorkspaceRoute
  AppColdproUnilabSystemsColdRoomRoute: typeof AppColdproUnilabSystemsColdRoomRoute
  AppColdproUnilabSystemsDehumidificationRoute: typeof AppColdproUnilabSystemsDehumidificationRoute
  AppColdproUnilabSystemsDxCompleteRoute: typeof AppColdproUnilabSystemsDxCompleteRoute
  AppColdproUnilabSystemsHeatPumpRoute: typeof AppColdproUnilabSystemsHeatPumpRoute
}

const AppColdproUnilabRouteChildren: AppColdproUnilabRouteChildren = {
  AppColdproUnilabWorkspaceRoute: AppColdproUnilabWorkspaceRoute,
  AppColdproUnilabSystemsColdRoomRoute: AppColdproUnilabSystemsColdRoomRoute,
  AppColdproUnilabSystemsDehumidificationRoute:
    AppColdproUnilabSystemsDehumidificationRoute,
  AppColdproUnilabSystemsDxCompleteRoute:
    AppColdproUnilabSystemsDxCompleteRoute,
  AppColdproUnilabSystemsHeatPumpRoute: AppColdproUnilabSystemsHeatPumpRoute,
}

const AppColdproUnilabRouteWithChildren =
  AppColdproUnilabRoute._addFileChildren(AppColdproUnilabRouteChildren)

interface AppColdproRouteChildren {
  AppColdproAssemblyRoute: typeof AppColdproAssemblyRoute
  AppColdproAuditRoute: typeof AppColdproAuditRoute
  AppColdproCatalogRoute: typeof AppColdproCatalogRoute
  AppColdproComponentsRoute: typeof AppColdproComponentsRoute
  AppColdproCurveRoute: typeof AppColdproCurveRoute
  AppColdproExportRoute: typeof AppColdproExportRoute
  AppColdproFichaTecnicaRoute: typeof AppColdproFichaTecnicaRoute
  AppColdproMapRoute: typeof AppColdproMapRoute
  AppColdproMontagemRoute: typeof AppColdproMontagemRoute
  AppColdproRecordRoute: typeof AppColdproRecordRoute
  AppColdproRegistryRoute: typeof AppColdproRegistryRoute
  AppColdproSimulationRoute: typeof AppColdproSimulationRoute
  AppColdproUnilabRoute: typeof AppColdproUnilabRouteWithChildren
  AppColdproIndexRoute: typeof AppColdproIndexRoute
}

const AppColdproRouteChildren: AppColdproRouteChildren = {
  AppColdproAssemblyRoute: AppColdproAssemblyRoute,
  AppColdproAuditRoute: AppColdproAuditRoute,
  AppColdproCatalogRoute: AppColdproCatalogRoute,
  AppColdproComponentsRoute: AppColdproComponentsRoute,
  AppColdproCurveRoute: AppColdproCurveRoute,
  AppColdproExportRoute: AppColdproExportRoute,
  AppColdproFichaTecnicaRoute: AppColdproFichaTecnicaRoute,
  AppColdproMapRoute: AppColdproMapRoute,
  AppColdproMontagemRoute: AppColdproMontagemRoute,
  AppColdproRecordRoute: AppColdproRecordRoute,
  AppColdproRegistryRoute: AppColdproRegistryRoute,
  AppColdproSimulationRoute: AppColdproSimulationRoute,
  AppColdproUnilabRoute: AppColdproUnilabRouteWithChildren,
  AppColdproIndexRoute: AppColdproIndexRoute,
}

const AppColdproRouteWithChildren = AppColdproRoute._addFileChildren(
  AppColdproRouteChildren,
)

interface AppRouteChildren {
  AppColdproRoute: typeof AppColdproRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppColdproRoute: AppColdproRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
