-- Add missing technical columns + provenance tracking to evaporator_coil_models
ALTER TABLE public.evaporator_coil_models
  ADD COLUMN IF NOT EXISTS sensible_ratio numeric,
  ADD COLUMN IF NOT EXISTS water_production_kgh numeric,
  ADD COLUMN IF NOT EXISTS global_coeff_w numeric,
  ADD COLUMN IF NOT EXISTS delta_h_log_kjkg numeric,
  ADD COLUMN IF NOT EXISTS atm_pressure_bar numeric,
  ADD COLUMN IF NOT EXISTS altitude_m numeric,
  ADD COLUMN IF NOT EXISTS air_density_in_kg_m3 numeric,
  ADD COLUMN IF NOT EXISTS rh_in_pct numeric,
  ADD COLUMN IF NOT EXISTS spec_hum_in_g_kg numeric,
  ADD COLUMN IF NOT EXISTS enthalpy_in_kjkg numeric,
  ADD COLUMN IF NOT EXISTS rh_out_pct numeric,
  ADD COLUMN IF NOT EXISTS spec_hum_out_g_kg numeric,
  ADD COLUMN IF NOT EXISTS enthalpy_out_kjkg numeric,
  ADD COLUMN IF NOT EXISTS refrigerant_mass_flow_kgh numeric,
  ADD COLUMN IF NOT EXISTS mass_velocity_kg_m2s numeric,
  ADD COLUMN IF NOT EXISTS vapour_velocity_ms numeric,
  ADD COLUMN IF NOT EXISTS liquid_velocity_ms numeric,
  ADD COLUMN IF NOT EXISTS manifold_pressure_drop_kpa numeric,
  ADD COLUMN IF NOT EXISTS total_ref_pressure_drop_kpa numeric,
  ADD COLUMN IF NOT EXISTS fin_thickness_mm numeric,
  ADD COLUMN IF NOT EXISTS tube_shape text,
  ADD COLUMN IF NOT EXISTS frontal_area_m2 numeric,
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS field_sources jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS validation_report jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Same for condenser_coil_models (and add the tracking + technical fields it lacks)
ALTER TABLE public.condenser_coil_models
  ADD COLUMN IF NOT EXISTS sensible_ratio numeric,
  ADD COLUMN IF NOT EXISTS global_coeff_w numeric,
  ADD COLUMN IF NOT EXISTS delta_t_log_k numeric,
  ADD COLUMN IF NOT EXISTS atm_pressure_bar numeric,
  ADD COLUMN IF NOT EXISTS altitude_m numeric,
  ADD COLUMN IF NOT EXISTS air_mass_flow_kgh numeric,
  ADD COLUMN IF NOT EXISTS face_velocity_ms numeric,
  ADD COLUMN IF NOT EXISTS air_density_in_kg_m3 numeric,
  ADD COLUMN IF NOT EXISTS rh_in_pct numeric,
  ADD COLUMN IF NOT EXISTS spec_hum_in_g_kg numeric,
  ADD COLUMN IF NOT EXISTS enthalpy_in_kjkg numeric,
  ADD COLUMN IF NOT EXISTS rh_out_pct numeric,
  ADD COLUMN IF NOT EXISTS spec_hum_out_g_kg numeric,
  ADD COLUMN IF NOT EXISTS enthalpy_out_kjkg numeric,
  ADD COLUMN IF NOT EXISTS air_pressure_drop_pa numeric,
  ADD COLUMN IF NOT EXISTS refrigerant_mass_flow_kgh numeric,
  ADD COLUMN IF NOT EXISTS mass_velocity_kg_m2s numeric,
  ADD COLUMN IF NOT EXISTS vapour_velocity_ms numeric,
  ADD COLUMN IF NOT EXISTS liquid_velocity_ms numeric,
  ADD COLUMN IF NOT EXISTS subcooling_k numeric,
  ADD COLUMN IF NOT EXISTS desuperheat_k numeric,
  ADD COLUMN IF NOT EXISTS refrigerant_pressure_drop_kpa numeric,
  ADD COLUMN IF NOT EXISTS manifold_pressure_drop_kpa numeric,
  ADD COLUMN IF NOT EXISTS total_ref_pressure_drop_kpa numeric,
  ADD COLUMN IF NOT EXISTS fin_thickness_mm numeric,
  ADD COLUMN IF NOT EXISTS tube_shape text,
  ADD COLUMN IF NOT EXISTS fin_material text,
  ADD COLUMN IF NOT EXISTS tube_material text,
  ADD COLUMN IF NOT EXISTS frontal_area_m2 numeric,
  ADD COLUMN IF NOT EXISTS nominal_air_temp_out_c numeric,
  ADD COLUMN IF NOT EXISTS confidence_score numeric,
  ADD COLUMN IF NOT EXISTS missing_fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS manual_overrides jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS field_sources jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS validation_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS description text;
