export const FIELD_ALIASES: Record<string, string[]> = {
  // ── Identificação ──────────────────────────────────────────────
  modelo_unico: [
    "modelo_unico",
    "unique_model",
    "model_unique",
    "modelo unico",
    "model_code",
    "codigo_modelo",
  ],
  modelo: ["modelo", "model", "model_name", "nome_modelo", "modelo_nome"],
  linha: ["linha", "line", "product_line", "linha_produto"],
  refrigerante: [
    "refrigerante",
    "refrigerant",
    "gas_refrigerante",
    "refrigerant_type",
    "tipo_refrigerante",
  ],
  compressor_codigo: [
    "compressor_codigo",
    "compressor_code",
    "compressor_model",
    "modelo_compressor",
    "codigo_compressor",
    "compressor",
  ],
  tensao_v: ["tensao_v", "voltage", "voltage_v", "tensao", "tensão", "tensao_volts"],
  numero_fases: ["numero_fases", "phases", "number_of_phases", "fases", "num_fases"],
  frequencia_hz: [
    "frequencia_hz",
    "frequency",
    "frequency_hz",
    "frequencia",
    "freq_hz",
    "frequência",
  ],

  // ── Evaporador ─────────────────────────────────────────────────
  evaporador_numero_fileiras: [
    "evaporador_numero_fileiras",
    "evap_rows",
    "evaporator_rows",
    "fileiras_evaporador",
    "numero_fileiras_evaporador",
    "evaporador_fileiras",
    "evaporator_number_of_rows",
    "rows_evaporator",
  ],
  evaporador_tubos_por_fileira: [
    "evaporador_tubos_por_fileira",
    "evap_tubes_per_row",
    "evaporator_tubes_per_row",
    "tubos_por_fileira_evaporador",
    "evaporador_tubos",
    "tubes_per_row_evaporator",
  ],
  evaporador_numero_circuitos: [
    "evaporador_numero_circuitos",
    "evap_circuits",
    "evaporator_circuits",
    "circuitos_evaporador",
    "numero_circuitos_evaporador",
    "evaporador_circuitos",
    "circuits_evaporator",
  ],
  evaporador_espacamento_aletas_mm: [
    "evaporador_espacamento_aletas_mm",
    "evap_fin_spacing_mm",
    "evaporator_fin_spacing_mm",
    "espacamento_aletas_evaporador",
    "fin_spacing_evaporator",
    "aletas_evaporador_mm",
    "evaporador_aletas_mm",
    "evaporator_fin_spacing",
  ],
  evaporador_comprimento_mm: [
    "evaporador_comprimento_mm",
    "evap_length_mm",
    "evaporator_length_mm",
    "eaporador_length_mm",
    "eaporador length_mm",
    "evaporador length_mm",
    "comprimento_evaporador",
    "comprimento evaporador",
    "evaporador comprimento mm",
    "length_evaporator_mm",
  ],
  evaporador_diametro_tubo_mm: [
    "evaporador_diametro_tubo_mm",
    "tubo_evap_mm",
    "evaporator_tube_diameter_mm",
    "diametro_tubo_evaporador",
    "tube_diameter_evaporator",
    "evaporador_tubo_mm",
    "evap_tube_diameter_mm",
  ],
  evaporador_espessura_tubo_mm: [
    "evaporador_espessura_tubo_mm",
    "esp_tubo_evap_mm",
    "evaporator_tube_thickness_mm",
    "espessura_tubo_evaporador",
    "tube_thickness_evaporator",
    "evaporador_esp_tubo_mm",
    "evap_tube_thickness_mm",
  ],
  evaporador_vazao_ventilador_m3h: [
    "evaporador_vazao_ventilador_m3h",
    "vazao_ventilador_evaporador_m3h",
    "evaporator_airflow_m3h",
    "airflow_evaporator_m3h",
    "vazao_evaporador",
    "evaporador_vazao_m3h",
    "evap_airflow_m3h",
    "evaporator_fan_airflow_m3h",
  ],
  evaporador_volume_interno_l: [
    "evaporador_volume_interno_l",
    "volume_interno_evaporador_l",
    "evaporator_internal_volume_l",
    "internal_volume_evaporator",
    "volume_evaporador_l",
    "evap_internal_volume_l",
  ],
  evaporador_area_troca_m2: [
    "evaporador_area_troca_m2",
    "area_superficie_troca_evaporador_m2",
    "evaporator_exchange_area_m2",
    "area_troca_evaporador",
    "exchange_area_evaporator",
    "evap_exchange_area_m2",
    "evaporador_area_m2",
  ],

  // ── Condensador ────────────────────────────────────────────────
  condensador_numero_fileiras: [
    "condensador_numero_fileiras",
    "cond_rows",
    "condenser_rows",
    "fileiras_condensador",
    "numero_fileiras_condensador",
    "condensador_fileiras",
    "condenser_number_of_rows",
    "rows_condenser",
  ],
  condensador_tubos_por_fileira: [
    "condensador_tubos_por_fileira",
    "cond_tubes_per_row",
    "condenser_tubes_per_row",
    "tubos_por_fileira_condensador",
    "condensador_tubos",
    "tubes_per_row_condenser",
  ],
  condensador_numero_circuitos: [
    "condensador_numero_circuitos",
    "cond_circuits",
    "condenser_circuits",
    "circuitos_condensador",
    "numero_circuitos_condensador",
    "condensador_circuitos",
    "circuits_condenser",
  ],
  condensador_espacamento_aletas_mm: [
    "condensador_espacamento_aletas_mm",
    "cond_fin_spacing_mm",
    "condenser_fin_spacing_mm",
    "espacamento_aletas_condensador",
    "fin_spacing_condenser",
    "aletas_condensador_mm",
    "condensador_aletas_mm",
    "condenser_fin_spacing",
  ],
  condensador_comprimento_mm: [
    "condensador_comprimento_mm",
    "cond_length_mm",
    "condenser_length_mm",
    "condensador length_mm",
    "comprimento_condensador",
    "comprimento condensador",
    "length_condenser_mm",
  ],
  condensador_diametro_tubo_mm: [
    "condensador_diametro_tubo_mm",
    "tubo_cond_mm",
    "condenser_tube_diameter_mm",
    "diametro_tubo_condensador",
    "tube_diameter_condenser",
    "condensador_tubo_mm",
    "cond_tube_diameter_mm",
  ],
  condensador_espessura_tubo_mm: [
    "condensador_espessura_tubo_mm",
    "esp_tubo_cond_mm",
    "condenser_tube_thickness_mm",
    "espessura_tubo_condensador",
    "tube_thickness_condenser",
    "condensador_esp_tubo_mm",
    "cond_tube_thickness_mm",
  ],
  condensador_vazao_ventilador_m3h: [
    "condensador_vazao_ventilador_m3h",
    "vazao_ventilador_condensador_m3h",
    "condenser_airflow_m3h",
    "airflow_condenser_m3h",
    "vazao_condensador",
    "condensador_vazao_m3h",
    "cond_airflow_m3h",
    "condenser_fan_airflow_m3h",
  ],
  condensador_volume_interno_l: [
    "condensador_volume_interno_l",
    "volume_interno_condensador_l",
    "condenser_internal_volume_l",
    "internal_volume_condenser",
    "volume_condensador_l",
    "cond_internal_volume_l",
  ],

  // ── Reaquecimento ──────────────────────────────────────────────
  reaquecimento_numero_fileiras: [
    "reaquecimento_numero_fileiras",
    "geometria_reaquecimento",
    "reheat_rows",
    "fileiras_reaquecimento",
    "numero_fileiras_reaquecimento",
    "reaquecimento_fileiras",
    "reheat_number_of_rows",
    "rows_reheat",
  ],
  reaquecimento_tubos_por_fileira: [
    "reaquecimento_tubos_por_fileira",
    "reaq_tubes_per_row",
    "reheat_tubes_per_row",
    "tubos_por_fileira_reaquecimento",
    "reaquecimento_tubos",
    "tubes_per_row_reheat",
  ],
  reaquecimento_numero_circuitos: [
    "reaquecimento_numero_circuitos",
    "reaq_circuits",
    "reheat_circuits",
    "circuitos_reaquecimento",
    "numero_circuitos_reaquecimento",
    "reaquecimento_circuitos",
    "circuits_reheat",
  ],
  reaquecimento_espacamento_aletas_mm: [
    "reaquecimento_espacamento_aletas_mm",
    "reaq_fin_spacing_mm",
    "reheat_fin_spacing_mm",
    "espacamento_aletas_reaquecimento",
    "fin_spacing_reheat",
    "aletas_reaquecimento_mm",
    "reaquecimento_aletas_mm",
    "reheat_fin_spacing",
  ],
  reaquecimento_comprimento_mm: [
    "reaquecimento_comprimento_mm",
    "reaq_length_mm",
    "reheat_length_mm",
    "reaquecimento length_mm",
    "comprimento_reaquecimento",
    "comprimento reaquecimento",
    "length_reheat_mm",
  ],
  reaquecimento_quantidade: [
    "reaquecimento_quantidade",
    "quantidade_reaquecimentos",
    "reheat_quantity",
    "number_of_reheats",
    "qtd_reaquecimento",
  ],
  reaquecimento_ventilador: [
    "reaquecimento_ventilador",
    "ventilador_reaquecimento",
    "reheat_fan",
    "fan_reheat",
    "ventilador_reaq",
  ],
  reaquecimento_vazao_ventilador_m3h: [
    "reaquecimento_vazao_ventilador_m3h",
    "reheat_airflow_m3h",
    "airflow_reheat_m3h",
    "vazao_reaquecimento",
    "reaquecimento_vazao_m3h",
    "reheat_fan_airflow_m3h",
  ],

  // ── Performance ────────────────────────────────────────────────
  capacidade_refrigeracao: [
    "capacidade_refrigeracao",
    "cooling_capacity",
    "capacidade_frigorifica",
    "capacidade frigorifica",
    "capacidade_frigorifica_kcal_h",
    "cooling_capacity_w",
    "cooling_capacity_kw",
    "cooling_capacity_kcal_h",
    "cooling_capacity_btu_h",
    "cooling_capacity_tr",
    "capacity_w",
    "capacity_kw",
    "capacity_kcal_h",
    "capacity_btu_h",
    "capacity_tr",
    "refrigeracao_kcal_h",
    "refrigeracao_w",
  ],
  capacidade_reaquecimento: [
    "capacidade_reaquecimento",
    "reheat_capacity",
    "reheat_capacity_w",
    "reheat_capacity_kw",
    "reheat_capacity_kcal_h",
    "capacidade_reaquecimento_kcal_h",
    "capacidade_reaquecimento_w",
  ],
  calor_rejeitado: [
    "calor_rejeitado",
    "heat_rejection",
    "rejected_heat",
    "calor_rejeitado_kcal_h",
    "calor_rejeitado_w",
    "heat_rejection_w",
    "heat_rejection_kcal_h",
  ],
  potencia_eletrica_total: [
    "potencia_eletrica_total",
    "total_electric_power",
    "total_power_w",
    "potencia_total_w",
    "potencia_eletrica",
    "electric_power",
    "power_w",
    "potencia_w",
  ],
  cop: ["cop", "coefficient_of_performance", "coeficiente_performance"],
  corrente_eletrica_estimada: [
    "corrente_eletrica_estimada",
    "estimated_current",
    "corrente_estimada",
    "current_a",
    "corrente_a",
    "fla",
    "full_load_amps",
  ],
  corrente_eletrica_partida: [
    "corrente_eletrica_partida",
    "starting_current",
    "corrente_partida",
    "lra",
    "locked_rotor_amps",
    "corrente_partida_a",
  ],
  temperatura_evaporacao_c: [
    "temperatura_evaporacao_c",
    "evaporation_temperature",
    "evap_temp_c",
    "temperatura_evaporacao",
    "temp_evaporacao",
    "evaporating_temperature_c",
  ],
  temperatura_condensacao_c: [
    "temperatura_condensacao_c",
    "condensation_temperature",
    "cond_temp_c",
    "temperatura_condensacao",
    "temp_condensacao",
    "condensing_temperature_c",
  ],
};
